[build]
  publish = "public"
  functions = "netlify/functions"

[functions]
  included_files = ["keys.json"]

[[redirects]]
  from = "/api/get-key"
  to = "/.netlify/functions/get-key"
  status = 200
